services:
    listener.chromedia.token_authenticated_request:
        class: Chromedia\SecurityTokenBundle\Listener\TokenAuthenticatedRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        calls:
            - [setAuthorizationHeaderKey, [%chromedia_security_token.authorization_header_key%]]
            - [setTokenProvider, [@chromedia_security_token.token_provider]]
            - [setAccessKeyRequestParameter, [%chromedia_security_token.access_key_request_parameter%]]
            - [setAccessTokenRequestParameter, [%chromedia_security_token.access_token_request_parameter%]]
        